export interface Language {
  code: string;
  name: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  // Top global languages by total speakers
  { code: "en", name: "English" },
  { code: "zh", name: "Chinese (Mandarin)" },
  { code: "hi", name: "Hindi" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "ar", name: "Arabic" },
  { code: "bn", name: "Bengali" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "ur", name: "Urdu" },
  { code: "id", name: "Indonesian" },
  { code: "de", name: "German" },
  { code: "ja", name: "Japanese" },
  { code: "mr", name: "Marathi" },
  { code: "te", name: "Telugu" },
  { code: "tr", name: "Turkish" },
  { code: "ta", name: "Tamil" },
  { code: "vi", name: "Vietnamese" },
  { code: "ko", name: "Korean" },
  { code: "it", name: "Italian" },
  { code: "gu", name: "Gujarati" },
  { code: "pl", name: "Polish" },
  { code: "uk", name: "Ukrainian" },
  { code: "fa", name: "Persian" },
  { code: "ml", name: "Malayalam" },
  { code: "kn", name: "Kannada" },
  { code: "or", name: "Odia" },
  { code: "my", name: "Burmese" },
  { code: "th", name: "Thai" },
  { code: "ms", name: "Malay" },
  { code: "pa", name: "Punjabi" },
  { code: "tl", name: "Tagalog" },
  { code: "sw", name: "Swahili" },
  // Major European languages
  { code: "nl", name: "Dutch" },
  { code: "ro", name: "Romanian" },
  { code: "az", name: "Azerbaijani" },
  { code: "kk", name: "Kazakh" },
  { code: "sv", name: "Swedish" },
  { code: "cs", name: "Czech" },
  { code: "el", name: "Greek" },
  { code: "hu", name: "Hungarian" },
  { code: "sr", name: "Serbian" },
  { code: "bg", name: "Bulgarian" },
  { code: "ca", name: "Catalan" },
  { code: "hr", name: "Croatian" },
  { code: "da", name: "Danish" },
  { code: "fi", name: "Finnish" },
  { code: "sk", name: "Slovak" },
  { code: "no", name: "Norwegian" },
  { code: "sq", name: "Albanian" },
  { code: "lt", name: "Lithuanian" },
  { code: "sl", name: "Slovenian" },
  { code: "lv", name: "Latvian" },
  { code: "et", name: "Estonian" },
  { code: "be", name: "Belarusian" },
  { code: "bs", name: "Bosnian" },
  { code: "mk", name: "Macedonian" },
  { code: "mt", name: "Maltese" },
  { code: "ga", name: "Irish" },
  { code: "cy", name: "Welsh" },
  { code: "is", name: "Icelandic" },
  { code: "ka", name: "Georgian" },
  { code: "hy", name: "Armenian" },
  { code: "he", name: "Hebrew" },
  { code: "eu", name: "Basque" },
  { code: "gl", name: "Galician" },
  { code: "lb", name: "Luxembourgish" },
];

export const SUPPORTED_LANGUAGE_CODES = new Set(
  SUPPORTED_LANGUAGES.map((lang) => lang.code)
);

export const MAX_LANGUAGES = 10;

// Map ISO 639-1 language codes to ISO 3166-1 alpha-2 country codes for flags.
// Some mappings are approximate because languages span multiple countries.
export const LANGUAGE_FLAG_MAP: Record<string, string> = {
  en: "gb",
  zh: "cn",
  hi: "in",
  es: "es",
  fr: "fr",
  ar: "sa",
  bn: "bd",
  pt: "pt",
  ru: "ru",
  ur: "pk",
  id: "id",
  de: "de",
  ja: "jp",
  mr: "in",
  te: "in",
  tr: "tr",
  ta: "in",
  vi: "vn",
  ko: "kr",
  it: "it",
  gu: "in",
  pl: "pl",
  uk: "ua",
  fa: "ir",
  ml: "in",
  kn: "in",
  or: "in",
  my: "mm",
  th: "th",
  ms: "my",
  pa: "in",
  tl: "ph",
  sw: "ke",
  nl: "nl",
  ro: "ro",
  az: "az",
  kk: "kz",
  sv: "se",
  cs: "cz",
  el: "gr",
  hu: "hu",
  sr: "rs",
  bg: "bg",
  ca: "es",
  hr: "hr",
  da: "dk",
  fi: "fi",
  sk: "sk",
  no: "no",
  sq: "al",
  lt: "lt",
  sl: "si",
  lv: "lv",
  et: "ee",
  be: "by",
  bs: "ba",
  mk: "mk",
  mt: "mt",
  ga: "ie",
  cy: "gb",
  is: "is",
  ka: "ge",
  hy: "am",
  he: "il",
  eu: "es",
  gl: "es",
  lb: "lu",
};

export function getLanguageName(code: string): string | undefined {
  return SUPPORTED_LANGUAGES.find((lang) => lang.code === code)?.name;
}

export function getLanguageFlag(code: string): string | undefined {
  return LANGUAGE_FLAG_MAP[code];
}
